version: '3'
services:
    # MySQL
    db:
        image: mysql:8.0
        container_name: mysql_host
        platform: linux/amd64 # m1 macの場合現時点でarm64対応していないので、platformを指定しないとエラーがでる
        environment: 
            MYSQL_ROOT_PASSWORD: root # 必要
            # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: local_db # 必要
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
        - ./docker/data:/var/lib/mysql # 設定しないとデータが消える
        ports: # localの3306番とコンテナの3306を結びつける
        - 3306:3306
